version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u212-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-v1-{{ checksum "pom.xml" }}
            - maven-repo-v1-
      - run:
          name: Build
          command: |
            java -version
            mvn -v
            mvn -B clean install
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ checksum "pom.xml" }}

workflows:
  version: 2
  build:
    jobs:
      - build